### ISSUE TITLE
The `m_eproperty` are not same in subgraph.

### ISSUE THREAD

**Issue by kenkangxgwe** [boostorg/graph#124]
Imagine we have a root graph g, and two sons of it g1 and g2.
If we use `edges(g1)` to get two iterators and cycle from one to the other to find an edge with index `i`,
we name its corresponding descriptor as `ed_1 = *e1_i`.
We use the same method in `g`, find an edge with index `i`, and convert it to g1's local edge descriptor, we name it `ed_2 = g1.global_to_local(*e_i)`.
And I found that their `m_eproperty` are not the same. Shouldn't these two be the same descriptor?

**Comment by kenkangxgwe** [comment]
> get two iterators and cycle from one to the other to find an edge with index i
```
    typename subgraph_t::edge_iterator e1_i, e1_i_end;
    typename subgraph_t::edge_descriptor ed1;
    for(tie(e1_i, e1_i_end) = edges(g1); e1_i != e1_i_end; ++e1_i)
    {
        if(get(boost::edge_index, g1, /* index */ 1) {
            ed1 = *e1_i;
        }
    }
```

Try this if you get a segmentation fault:
``` c++
template<typename subgraph_t>
void global_local_convertion_test(subgraph_t &g)
{
    subgraph_t r_g = g.root();
    typename subgraph_t::edge_iterator er_i, er_i_end;
    for(tie(er_i, er_i_end) = edges(r_g); er_i != er_i_end; ++er_i)
    {
        if(get(boost::edge_index, r_g, *er_i) == 1)
        {
            g[g.global_to_local(*er_i)];
        }
    }
    typename subgraph_t::const_children_iterator gi, gi_end;
    boost::tie(gi, gi_end) = g.children();
    for(; gi != gi_end; ++gi)
    {
        global_local_convertion_test(*gi);
    }
}
```

**Comment by kenkangxgwe** [comment]
> So are you saying that the edge between two vertices in a subgraph is not the same edge as between those two vertices in the full graph?
I tried to say the edge between two vertices in a subgraph is not the same edge as the edge between the same two vertices full graph **after I convert it from global to local**

**Comment by anadon** [comment]
That global to local might be to have alternate sets of edges in subgraphs.  I'll check it out.  

Please provide the output from valgrind running your test case in a gist.

**Comment by anadon** [comment]
```
    edge_descriptor global_to_local(edge_descriptor e_global) const
    { return is_root() ? e_global : (*m_local_edge.find(get(get(edge_index, root().m_graph), e_global))).second; }
```

It looks like subgraphs can have alternate sets of edges.  I disagree with this design choice and it is opaque, but it is already set.

That moves focus to whether a subgraph's included edges at creation should be left as default, copied from the next level up, or it is obviously incorrect.  I'll hit this later.  I've been up since 3AM local time, past 4:30 now and I'm dead tired.

**Comment by kenkangxgwe** [comment]
There you go the log:
https://gist.github.com/kenkangxgwe/af4ccb3cec3ae446dc5d69df2184caba

BTW, it seems that we are in the same Time Zone. Good night, bro.

**Comment by Becheler** [comment]
Hi @kenkangxgwe !
Picking this up. Took me a while, I had issues reproducing the problem, but I think I found the problem and the solution.

Quick summary: `subgraph::global_to_local(edge_descriptor)` does an unchecked dereference of `m_local_edge.find()`. When called with an edge not in the subgraph, this is UB -> memory corruption. Reproducer below. Proposed fix mirrors the existing safe vertex version.

## Reproducer

Please compile with `-std=c++14 -g -O1 -fsanitize=address,undefined -fno-omit-frame-pointer`

### User case

This reproduces what I could understand of the user case. [See on Compiler Explorer](https://godbolt.org/z/dqW9h9nG1)

```cpp
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/subgraph.hpp>
#include <iostream>

using namespace boost;

using G = subgraph<adjacency_list<vecS, vecS, bidirectionalS,
    property<vertex_color_t, int>,
    property<edge_index_t, unsigned long,
        property<edge_weight_t, int>>,
    no_property, listS>>;

// User's test function: walks the subgraph tree and,
// for each subgraph, looks up root edges with edge_index == 1 via
// global_to_local. The recursion visits subgraphs that don't contain
// every root edge, triggering the bug
template <typename SG>
void global_local_conversion_test(SG& g) {
    SG& r_g = g.root();
    typename SG::edge_iterator ei, ei_end;
    for (boost::tie(ei, ei_end) = edges(r_g); ei != ei_end; ++ei) {
        if (get(edge_index, r_g, *ei) == 1) {
            // BUG: when this is called on a subgraph that doesn't contain the root edge with index 1, global_to_local
            // dereferences end() and corrupts memory
            auto local = g.global_to_local(*ei);
            (void)g[local];
        }
    }
    typename SG::children_iterator ci, ci_end;
    for (boost::tie(ci, ci_end) = g.children(); ci != ci_end; ++ci) {
        global_local_conversion_test(*ci);
    }
}

int main() {
    std::cout.setf(std::ios::unitbuf);

    // Build a root graph: a 5-node path plus a back edge
    G root(5);
    add_edge(0, 1, root);
    add_edge(1, 2, root);
    add_edge(2, 3, root);
    add_edge(3, 4, root);
    add_edge(0, 4, root);

    // g1 covers the "left half": vertices {0, 1, 2}
    // Contains edge (1,2) which has edge_index 1
    G& g1 = root.create_subgraph();
    add_vertex(0, g1);
    add_vertex(1, g1);
    add_vertex(2, g1);

    // g2 covers the "right half": vertices {2, 3, 4}
    // Does NOT contain edge (1,2) (vertex 1 isn't in g2)
    G& g2 = root.create_subgraph();
    add_vertex(2, g2);
    add_vertex(3, g2);
    add_vertex(4, g2);

    std::cout << "Walking subgraph tree...\n";
    global_local_conversion_test(root);
    std::cout << "done\n";
}
```
Output:
```
Program returned: 1
Program stdout
Walking subgraph tree...
Program stderr
=================================================================
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7034f8de03b0 at pc 0x00000041d7d1 bp 0x7fffb7eb7830 sp 0x7fffb7eb7828
READ of size 24 at 0x7034f8de03b0 thread T0
    #0 0x00000041d7d0 in boost::subgraph<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<boost::vertex_color_t, int, boost::no_property>, boost::property<boost::edge_index_t, unsigned long, boost::property<boost::edge_weight_t, int, boost::no_property> >, boost::no_property, boost::listS> >::global_to_local(boost::detail::edge_desc_impl<boost::bidirectional_tag, unsigned long>) const /app/boost/include/boost/graph/subgraph.hpp:231
    #1 0x00000041d7d0 in void global_local_conversion_test<boost::subgraph<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<boost::vertex_color_t, int, boost::no_property>, boost::property<boost::edge_index_t, unsigned long, boost::property<boost::edge_weight_t, int, boost::no_property> >, boost::no_property, boost::listS> > >(boost::subgraph<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<boost::vertex_color_t, int, boost::no_property>, boost::property<boost::edge_index_t, unsigned long, boost::property<boost::edge_weight_t, int, boost::no_property> >, boost::no_property, boost::listS> >&) /app/example.cpp:26
    #2 0x00000041fe94 in void global_local_conversion_test<boost::subgraph<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<boost::vertex_color_t, int, boost::no_property>, boost::property<boost::edge_index_t, unsigned long, boost::property<boost::edge_weight_t, int, boost::no_property> >, boost::no_property, boost::listS> > >(boost::subgraph<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<boost::vertex_color_t, int, boost::no_property>, boost::property<boost::edge_index_t, unsigned long, boost::property<boost::edge_weight_t, int, boost::no_property> >, boost::no_property, boost::listS> >&) /app/example.cpp:32
    #3 0x000000402a03 in main /app/example.cpp:62
    #4 0x7324f9a29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 095c7ba148aeca81668091f718047078d57efddb)
    #5 0x7324f9a29e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 095c7ba148aeca81668091f718047078d57efddb)
    #6 0x000000402334 in _start (/app/output.s+0x402334) (BuildId: 48c0a49637f1fdbdd7c92b82bd0ec6e11262ab85)

0x7034f8de03b0 is located 0 bytes after 240-byte region [0x7034f8de02c0,0x7034f8de03b0)
allocated by thread T0 here:
    #0 0x7324fa81289b in operator new(unsigned long) (/opt/compiler-explorer/gcc-15.1.0/lib64/libasan.so.8+0x12289b) (BuildId: 7200a781b43e8ef5b412151c63de00f2b1a73d8c)
    #1 0x00000040da46 in boost::subgraph<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<boost::vertex_color_t, int, boost::no_property>, boost::property<boost::edge_index_t, unsigned long, boost::property<boost::edge_weight_t, int, boost::no_property> >, boost::no_property, boost::listS> >::create_subgraph() /app/boost/include/boost/graph/subgraph.hpp:183
    #2 0x000000402935 in main /app/example.cpp:56
    #3 0x7324f9a29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 095c7ba148aeca81668091f718047078d57efddb)

SUMMARY: AddressSanitizer: heap-buffer-overflow /app/boost/include/boost/graph/subgraph.hpp:231 in boost::subgraph<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<boost::vertex_color_t, int, boost::no_property>, boost::property<boost::edge_index_t, unsigned long, boost::property<boost::edge_weight_t, int, boost::no_property> >, boost::no_property, boost::listS> >::global_to_local(boost::detail::edge_desc_impl<boost::bidirectional_tag, unsigned long>) const
Shadow bytes around the buggy address:
  0x7034f8de0100: 00 00 00 00 00 00 fa fa fa fa fa fa fa fa fa fa
  0x7034f8de0180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7034f8de0200: 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa
  0x7034f8de0280: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x7034f8de0300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7034f8de0380: 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa
  0x7034f8de0400: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7034f8de0480: 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa
  0x7034f8de0500: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7034f8de0580: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7034f8de0600: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1==ABORTING
```

### Minimal reproducer

After some experiments I could come up with a minimal reproducer. [See on Compiler Explorer](https://godbolt.org/z/oKrbYj5cc)

```cpp
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/subgraph.hpp>

using namespace boost;

using G = subgraph<adjacency_list<vecS, vecS, bidirectionalS,
    no_property,
    property<edge_index_t, unsigned long>>>;

int main() {
    G root(3);
    add_edge(0, 1, root);   // edge_index 0
    add_edge(1, 2, root);   // edge_index 1

    // sg contains only vertices {1, 2} -> only edge (1,2) is in sg
    // Edge (0,1) is in root but NOT in sg
    G& sg = root.create_subgraph();
    add_vertex(1, sg);
    add_vertex(2, sg);

    // Get the edge (0,1) from root
    G::edge_iterator ei, ei_end;
    boost::tie(ei, ei_end) = edges(root);
    auto edge_not_in_sg = *ei;

    // BUG: global_to_local doesn't check whether the edge is actually in sg.
    // m_local_edge.find(0) returns end(), and dereferencing it is UB.
    auto local = sg.global_to_local(edge_not_in_sg);
    (void)sg[local];  // ASAN: heap-buffer-overflow here.
}
```

Output:

```
Program returned: 1
Program stderr
=================================================================
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7b03023e0130 at pc 0x000000412798 bp 0x7ffd3b479e00 sp 0x7ffd3b479df8
READ of size 24 at 0x7b03023e0130 thread T0
    #0 0x000000412797 in boost::subgraph<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::no_property, boost::property<boost::edge_index_t, unsigned long, boost::no_property>, boost::no_property, boost::listS> >::global_to_local(boost::detail::edge_desc_impl<boost::bidirectional_tag, unsigned long>) const /app/boost/include/boost/graph/subgraph.hpp:231
    #1 0x000000402ccb in main /app/example.cpp:28
    #2 0x7df303029d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 095c7ba148aeca81668091f718047078d57efddb)
    #3 0x7df303029e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 095c7ba148aeca81668091f718047078d57efddb)
    #4 0x000000402324 in _start (/app/output.s+0x402324) (BuildId: 97eb7cf927060cc16f80e14ece993f6cfccdc91e)

0x7b03023e0130 is located 0 bytes after 240-byte region [0x7b03023e0040,0x7b03023e0130)
allocated by thread T0 here:
    #0 0x7df303d1e89b in operator new(unsigned long) (/opt/compiler-explorer/gcc-15.1.0/lib64/libasan.so.8+0x12289b) (BuildId: 7200a781b43e8ef5b412151c63de00f2b1a73d8c)
    #1 0x00000040d7a8 in boost::subgraph<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::no_property, boost::property<boost::edge_index_t, unsigned long, boost::no_property>, boost::no_property, boost::listS> >::create_subgraph() /app/boost/include/boost/graph/subgraph.hpp:183
    #2 0x000000402679 in main /app/example.cpp:17
    #3 0x7df303029d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 095c7ba148aeca81668091f718047078d57efddb)

SUMMARY: AddressSanitizer: heap-buffer-overflow /app/boost/include/boost/graph/subgraph.hpp:231 in boost::subgraph<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, boost::no_property, boost::property<boost::edge_index_t, unsigned long, boost::no_property>, boost::no_property, boost::listS> >::global_to_local(boost::detail::edge_desc_impl<boost::bidirectional_tag, unsigned long>) const
Shadow bytes around the buggy address:
  0x7b03023dfe80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7b03023dff00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7b03023dff80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7b03023e0000: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x7b03023e0080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7b03023e0100: 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa
  0x7b03023e0180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7b03023e0200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7b03023e0280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7b03023e0300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7b03023e0380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1==ABORTING
```

## The underlying problem

`subgraph::global_to_local(edge_descriptor)` is only defined when the input edge is actually in the subgraph. For edges not in the subgraph, the behavior is undefined (it dereferences `end()`). But its signature, name, and documentation all present it as being well-defined irrespective of the input.

https://github.com/boostorg/graph/blob/c1f4786e118311d45702c58e270046cb144cdde4/include/boost/graph/subgraph.hpp#L226-L232

In the source we see that there is a `std::map` iterator unconditional dereference of `m_local_edge.find(...).` : if `find()` returns `end()` (edge not in subgraph), this is UB (here memory violation).

- The signature edge_descriptor -> edge_descriptor says "give me any edge, I'll give you an edge back."
- The name "global to local" describes a transformation, not a search.
- The docs say "converts a global edge descriptor to the corresponding local edge descriptor" : no precondition, no failure mode.

## Proposed fix

There are two functions `find_edge` and `find_vertex` coming with a more "searchy" semantics (undocumented) that returns pairs if items exist in the subgraph:

https://github.com/boostorg/graph/blob/c1f4786e118311d45702c58e270046cb144cdde4/include/boost/graph/subgraph.hpp#L234-L257

We should fix `global_tol_local` to mirror what the equivalent function for vertices is doing:

https://github.com/boostorg/graph/blob/c1f4786e118311d45702c58e270046cb144cdde4/include/boost/graph/subgraph.hpp#L208-L216

Essentially replacing the body with a inner call to the safe version, and an assertion to at least have a clear error in debug mode:

```cpp
edge_descriptor global_to_local(edge_descriptor e_global) const
{
    if (is_root()) return e_global;
    edge_descriptor e_local;
    bool in_subgraph;
    boost::tie(e_local, in_subgraph) = this->find_edge(e_global);
    BOOST_ASSERT_MSG(in_subgraph, "global_to_local: edge is not in this subgraph. Use find_edge() to check membership first.");
    return e_local;
}
```

We should also make a serious update:
- give a solid unit test of subgraphs (tested through algorithms, no dedicated `subgraph_test.cpp` so far), including testing stability of descriptors and interface in recursive subgraphs, as the user tried to do.
- document the existence of `find_edge` and `find_vertex`
- document the preconditions of `global_to_local` and `local_to_global`
